<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7322" started-at="2019-06-02T16:43:08Z" finished-at="2019-06-02T16:43:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7322" started-at="2019-06-02T16:43:08Z" finished-at="2019-06-02T16:43:15Z">
      <class name="frame.work.Module1">
        <test-method status="PASS" signature="property()[pri:0, instance:frame.work.Module1@3bfdc050]" name="property" is-config="true" duration-ms="4981" started-at="2019-06-02T16:43:08Z" finished-at="2019-06-02T16:43:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- property -->
        <test-method status="FAIL" signature="testcasenumber()[pri:0, instance:frame.work.Module1@3bfdc050]" name="testcasenumber" duration-ms="15" started-at="2019-06-02T16:43:13Z" description="Type text in Google search engine" finished-at="2019-06-02T16:43:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at frame.work.MR.GetTiltle(MR.java:37)
at frame.work.Module1.testcasenumber(Module1.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcasenumber -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:frame.work.Module1@3bfdc050]" name="CloseBrowser" is-config="true" duration-ms="2300" started-at="2019-06-02T16:43:13Z" finished-at="2019-06-02T16:43:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- frame.work.Module1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
